### PR TITLE
Scanning using PendingIntent

### PR DESCRIPTION
**Pull request by philips77**
On pre-Oreo it is using ScannerService to emulate required behavior. Service is added to AndroidManifest automatically.
Not tested yet.

### CODE REVIEW

**Comment by piotr-pawlowski** [comment]
Scanning in background is a strange thing so I think you should not support it because there will be lots of issues. First of all Android 7+ will kill non-foreground service after app is closed. Please take a look on AltBeacon library and their troubles with long-term background scanning. Some devices stop scanning in background when screen is off. AltBeacon library uses JobScheduler and AlarmManager to provide long-term scanning in background. But there are still problems and it doesn't work reliably.

https://github.com/AltBeacon/android-beacon-library

**Comment by philips77** [comment]
As of my knowledge Android 8 started killing non foreground services. For 8+ this lib would not use service at all, since startScan with Pending Intent is available. For older systems imo this will work, but indeed it is not guaranteed to work. For example, removing a task from recents kills the service, as it doesn't work in it's own process, etc. But isn't it better than not having it and forcing devs to implement it on their own?

**Comment by bernard-trackster** [comment]
Requirement of my project is to scan for BLEs in the background every 5 minutes. I have implemented this functionality using AlarmManager but when I call the SDK to start scanning it does not work as call back is not getting called at all. and after few seconds it stops:

`01-21 23:53:05.130 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeacon Infos size::  3
01-21 23:53:05.132 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeaconInfos size::  3
01-21 23:54:00.023 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver 5 minutes
01-21 23:54:00.024 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver can be called
01-21 23:54:00.113 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeaconInfos size::  0
01-21 23:54:00.114 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStartScan
01-21 23:54:05.135 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStopScan
01-21 23:54:05.135 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeacon Infos size::  0
01-21 23:55:00.017 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver 5 minutes
01-21 23:55:00.018 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver can be called
01-21 23:55:00.097 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeaconInfos size::  0
01-21 23:55:00.097 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStartScan
01-21 23:55:05.117 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStopScan
01-21 23:55:05.117 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeacon Infos size::  0
01-21 23:56:20.160 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver 5 minutes
01-21 23:56:20.161 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver can be called
01-21 23:56:20.234 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeaconInfos size::  0
01-21 23:56:20.235 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStartScan
01-21 23:56:25.256 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStopScan
01-21 23:56:25.256 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeacon Infos size::  0
01-21 23:57:00.021 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver 5 minutes
01-21 23:57:00.022 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: BLE receiver can be called
01-21 23:57:00.105 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeaconInfos size::  0
01-21 23:57:00.105 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStartScan
01-21 23:57:05.124 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: onStopScan
01-21 23:57:05.125 22609-22609/com.devloper.tackerster D/BLEScanBroadCastReceiver: mBeacon Infos size::  0`

**Comment by philips77** [comment]
Hi @bernard-trackster, how is your post related to the PR?

**Pull request merged**
