### PR TITLE
Added basic support for tests

### PR DESCRIPTION
**Pull request by aldoborrero**
Mostly as described in issue #6 

I've adapted original AOSP tests to the library.Also, I've added unit tests to Objects class.

I bumped version to 1.0.0 and updated gradle versions.

Should we consider adding more tests to more specific parts of the code?

### CODE REVIEW

**Comment by philips77** [comment]
Hi! Thanks so much for the PR. I will take a look at it today and come back to you.

**Comment by aldoborrero** [comment]
Hi @philips77 any news? 

Thanks :)

**Comment by philips77** [comment]
Hi, thanks for a gentle ping :)
I'll merge and release the version now. I hope you tested your tests... I have no time to look through it properly :(

**Comment by aldoborrero** [comment]
Thanks! Let's have finger crossed.

I plan to add more tests than AOSP currently has. But I'll create another PR to track status there.

**Pull request merged**
