### PR TITLE
Bugfix: empty or no filter should match all scan results?

### PR DESCRIPTION
**Pull request by unverbraucht**
I'm not 100% sure about this but my understanding is that no filter or an empty one should case all scan results to get passed onto the callback.

### CODE REVIEW

**Comment by philips77** [comment]
Yes, i guess you're right. I didn't try putting an empty filter list but I guess no list should have the same result as an empty list. Thanks!

**Comment by philips77** [comment]
Hi, I've just pushed version 0.2.0 on jcenter. It has all the merged PRs included.

**Comment by unverbraucht** [comment]
Awesome :)

**Comment by philips77** [comment]
Thanks again for contributing!

**Pull request merged**
